### ISSUE TITLE
Switches for sensors

### ISSUE THREAD

**Issue by krismarc** [alengwenus/pypck#123]
Hi @alengwenus,

wouldn't it be valuable to create switches in addition to sensors which would be doing key locks for on and off operations? The lock state is known. So I assume, such a switch would be fully reliable.
At the moment, we need to template all of this and reapeat all the LCN addressing which is already known by configuration?

By doing so, we would have eg. an option to turn on and off PIMs and GUSes out of the box.
..eventually, PIM/GUS declaration possibility in configuration. Which would create such a switch if user requested so.

template:
![image](https://github.com/user-attachments/assets/3e0e56c9-45ef-485f-b5b6-38201ce6a4c3)

configuration:
![image](https://github.com/user-attachments/assets/ae97a87e-f153-43ce-89fc-127c3a488d4f)

things like this are rather nasty:
![image](https://github.com/user-attachments/assets/26aa9c3e-6750-4d76-a751-d2383af0e63e)

Best regards,
K.M.

**Comment by alengwenus** [comment]
It should be possible to implement switches for the key-locks (and for the regulator-locks as well I guess). I wanted to rework the service actions anyway. So once the switches are implemented I would remove the sensors and the service actions for these two lock types.

**Comment by krismarc** [comment]
Sounds good 😀 Not sure how this would potentially break actual people setups and if keeping both wouldn't be better for backward compatibility. I leave it up to you.

**Comment by alengwenus** [comment]
Available from HA 2024.11.0

**Comment by krismarc** [comment]
Thanks! Worked well for me! Btw. Sorting by module numer doesnt work. Not sure at this point if thats any how under your control.

**Comment by alengwenus** [comment]
> Thanks! Worked well for me! Btw. Sorting by module numer in integration configuration doesnt work. Not sure at this point if thats any how under your control.

https://github.com/alengwenus/lcn-frontend/issues/27
