### ISSUE TITLE
PCK listener sample. Development tips.

### ISSUE THREAD

**Issue by krismarc** [alengwenus/pypck#125]
Hi @alengwenus,

I've already made few small attempts to get some closer/deeper understanding of your lib so I could test/try things myself. However, I don't know LCN's/PCK nor HA's api yet. I tried to reverse engineer a bit what happens in HA's core LCN's module in order to understand how do you listen what's sent by LCN-PCHK. Somehow I find it yet difficult.

Having a sample, which would let me see what's sent/processed by LCN would be a good starting point, so I could start seeing and putting some debug within the lib. I'm not really developer, however, I'm doing various troubleshooting for living and usually it's a matter of time for me to understand someone's code. I just need a fair starting point :) Later on, I could follow all methods calls chains to understand what you actually do in your code. 

If I am not wrong, you listen to all messages sent by LCN-PCHK, and out of them you consider them virtually as devices in HA.
I'd like to mimic such a listener, that I could see PCK messages etc. So I can exclude HA itself from initial learning of this lib/pck protocol.

btw, is there any PCK spec/sdk available anywhere?or did you reverse engineer all of this completely yourself? 😄

I've got some aspirations to become junior maintainer here and learn some stuff from all of this. I'm going to be linked with LCN for many upcoming years as my home is based on it, so having deeper knowledge might be beneficial in the future for me.

Best regards,
K.M.

**Comment by krismarc** [comment]
well..,

I've pasted your HA's init into chatgpt and asked it to make it work without HA.
Actually it worked with the first attempt :)

```
import asyncio
import logging
from pypck.connection import PchkConnectionManager
from pypck.inputs import Input

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

async def handle_input(inp: Input):
    """Process received input from the LCN bus."""
    # Check if the input is a ModInput (you can check for other types if needed)
    if isinstance(inp, pypck.inputs.ModInput):
        logger.info(f"Received input: {inp}")

async def main():
    # Replace these with your actual connection details
    ip_address = '***'
    port = 4114
    username = 'lcn'
    password = '***'

    # Initialize the connection
    connection = PchkConnectionManager(ip_address, port, username, password)

    try:
        # Establish the connection
        await connection.async_connect(timeout=15)
        logger.info("Connected to LCN bus.")

        # Register a callback for incoming inputs
        connection.register_for_inputs(handle_input)

        # Keep the script running to listen for incoming commands
        while True:
            await asyncio.sleep(0.3)

    except Exception as e:
        logger.error(f"An error occurred: {e}")
    finally:
        await connection.async_close()

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by krismarc** [comment]
Strange observation. Not sure if I correctly understand this.
https://github.com/alengwenus/pypck/blob/3aec239c8311141edce7333ad3d682c3eb4c7b5e/pypck/connection.py#L114
Am I supposed to see all reader messages on the bus here (except 'writer')? Actually, not all commands I send from LCN-PRO are present in 'data'. 
LCN-Visu is my coupler.

**Comment by alengwenus** [comment]
> Strange observation. Not sure if I correctly understand this.
> 
> https://github.com/alengwenus/pypck/blob/3aec239c8311141edce7333ad3d682c3eb4c7b5e/pypck/connection.py#L114
> 
> 
> Am I supposed to see all reader messages on the bus here (except 'writer')? Actually, not all commands I send from LCN-PRO are present in 'data'.
> LCN-Visu is my coupler.

Not all bus telegrams have a representation in the PCK protocol and are therefore not passed to the socket by the LCN-VISU. So yes, it might be that you do not see all commands sent by LCN-PRO.

**Comment by krismarc** [comment]
Ok, thank you, you have updated before my next question 'how does LCN-PRO works then?' 😄

So it's strange. I can see shutter height changing but not the command sent to trigger it (via shutter position commands)..
```
DEBUG:pypck.connection:from PCHK: :M000012P2099
DEBUG:pypck.connection:from PCHK: :M000012P2096
DEBUG:pypck.connection:from PCHK: :M000012P2093
DEBUG:pypck.connection:from PCHK: :M000012P2090
DEBUG:pypck.connection:from PCHK: :M000012P2088
DEBUG:pypck.connection:from PCHK: :M000012P2091
DEBUG:pypck.connection:from PCHK: :M000012P2095
DEBUG:pypck.connection:from PCHK: :M000012P2098
```
While for blades angle both are not sent back by VISU - command nor actual state.

Wondering then, why they did so 😄 ..should we start looking at hexes processed by LCN-PRO? 😅

**Comment by alengwenus** [comment]
Entities in HA will send "commands" and set their states according to status "messages". Only status messages from the bus are therefore translated to PCK. Therefore, you will never see "commands" from the bus translated to PCK.
This is what LCN-VISU does:
- PCK _commands_ are translated to telegrams and sent **to** the bus.
- Status _messages_ are received **from** the bus and translated to PCK.

This means, pypck only has to _parse_ PCK status messages and _create_ PCK commands. Not the other way around (as it makes no sense).

**Comment by krismarc** [comment]
Ah, does it mean, we can still send all possible commands via your client (if we know the pattern)? I just found eg. beep command in your code, I can't see a message produced by it, however it rings :)

**Comment by alengwenus** [comment]
Yes, all PCK commands known to LCN-VISU can be sent, of course.
In addition there are PCK commands which allow to send any "command" telegrams in plain bytes (if you know them).
But you will never be able to receive all telegrams from the bus if no corresponding PCK command exists. They will simply be "blocked" by the LCN-VISU.

**Comment by krismarc** [comment]
> This means, pypck only has to parse PCK status messages and create PCK commands. Not the other way around (because it makes no sense).
does it mean, there's no status message for eg. setting blade angle? So we can just assume their state based on command sent? If you use steps, somehow LCN knows on which actual step it is, if we run again to set it to the same step, it won't move the shutter.

**Comment by alengwenus** [comment]
As far as I know the modules store the position internally (time based)... and maybe also the shutter angle? But as I said: I never was interested in investigating this in detail as I did not need it.

**Comment by krismarc** [comment]
Now this starts to make sense to me!
so I can lookup actual commands syntax (header + 'pck') here:
https://github.com/alengwenus/pypck/blob/3aec239c8311141edce7333ad3d682c3eb4c7b5e/pypck/connection.py#L164

How do you discover pck syntax? While header seems to rather easy, I've no clue where you have taken the other part from:
eg. beep: b'>M000032!**PIS001**\n'

Is it anywhere described/explained? or one had to brute force it/analyze tcp calls? As I can see, there's openhab's java implementation which could be also a good source of someone's analyze.

**Comment by alengwenus** [comment]
A little bit of everything. 😉

**Comment by krismarc** [comment]
Well.., I'll try to dig around. 
I believe, you should just go there to Rethen and shake a hand with Issendorff's boss or meet with their DEVs. They should officially start to support open source 😃 or at least provide pck spec.

**Comment by krismarc** [comment]
I'd not dare if I'd be native ger living 200km from them 😄 (you should feel triggered now 😃)

**Comment by krismarc** [comment]
Actually, it is official implementation for openhab made by them!
![image](https://github.com/user-attachments/assets/fb102df2-4cb3-4c0a-b130-245df243c0a3)
https://github.com/Issendorff/openhab/tree/master/bundles/binding/org.openhab.binding.lcn

You should propose to them. Officially and commercially. I'd be not surprised that they would be interested. I believe HA has taken over openhab as concurent platform.

**Comment by krismarc** [comment]
I'd say it's the other way around. They would need to open their eyes and make it somehow open if they want to survive on the market (and I believe that openhab/VISU initiative was their attempt). Even IBM does that (lots of their software is already opensource and they are just stick to paid support). They are good in hardware and they should be stick to it. Even if this would be not their commerical target (I assume, their target are bigger installations), they would benefit from marketing point of view. Otherwise eg. KNX kills them.
