### ISSUE TITLE
mypy error "str" has no attribute "decode" in pck_commands.py

### ISSUE THREAD

**Issue by maximilianriemensberger** [alengwenus/pypck#17]
While adding type annotations I ran into a problem with
https://github.com/alengwenus/pypck/blob/70c936301b73f7b615ee7e9a9802f2720b4460da/pypck/pck_commands.py#L897
It calls decode on a python string. mypy complains about it since str has no decode method. I think not doing anything is actually the right choice since str is utf-8 and LCN encoding is also utf-8.

**Comment by alengwenus** [comment]
Thanks @maximilianriemensberger!
Despite the docstring the `part` parameter should be of type `bytes`.
I fixed the docstring (2697508341cf8b56134320dfa9f637276d7729fd).
Could you please recheck if mypy is sattisfied?

**Comment by maximilianriemensberger** [comment]
Yes, using `bytes` instead of `str` fixes the error. Thanks!

FYI, I'm working on adding type annotations.  The current WIP state is tracked in https://github.com/maximilianriemensberger/pypck/tree/support-mypy-and-type-annotations.  I got all but the module.py and connection.py done. I'll submit a PR when I get all files `mypy --strict` clean.
