### ISSUE TITLE
LcnAddr::is_valid not consistent with doc

### ISSUE THREAD

**Issue by maximilianriemensberger** [alengwenus/pypck#18]
The documentation mentions that `5..254` are valid group and module addresses. However, `is_valid ` checks for `< 254`, see 

https://github.com/alengwenus/pypck/blob/70c936301b73f7b615ee7e9a9802f2720b4460da/pypck/lcn_addr.py#L107-L112

and 

https://github.com/alengwenus/pypck/blob/70c936301b73f7b615ee7e9a9802f2720b4460da/pypck/lcn_addr.py#L121-L126

In both cases I think `<= 254` would be correct.

**Comment by alengwenus** [comment]
Thanks a lot @maximilianriemensberger! 
Address range is fixed in 92df89d.
