### ISSUE TITLE
Threaded API

### ISSUE THREAD

**Issue by alengwenus** [alengwenus/pypck#3]
Pypck strongly depends on Python's Asyncio library. Although this is very ressource-conserving it always needs an event loop. This prohibits easy usage from an interactive Python interpreter session or a Jupyter notebook. Such an interactive session would allow investigations on the behavior of PCK commands on the whole LCN system.

A threaded API which wraps the event loop has to be implemented.

**Comment by maximilianriemensberger** [comment]
I played around with pypck interactively today in ipython. Except for a few minor issues, it actually works quite nicely.

 However, the interactive async support in ipython is somewhat special as they start ans stop the event loop for each prompt. See https://ipython.readthedocs.io/en/stable/interactive/autoawait.html# . For example, ipython only starts the event loop if there is a top-level async something involved. This means that non-async functions like `PchkConnectionManager.get_address_conn()` that internally invoke async stuff that relies on a event loop context for things like `create_task` fails to work. There is workarounds to make it work again (e.g. add an `await asyncio.sleep(0)` to the command list).

Still, I think ipython with autoawait support is probably the fastest and lowest effort solution to making pypck usable in a REPL. For experimentation, prototying etc. this would actually be pretty awesome.  Much better than handcooking Pck commands and telnet them into Pchk or netcat'ing pre-cooked pck commands into Pchk.

I'll work on a PR that straitens out some of the issues to make most of the basic things work in ipython with autoawait.

**Comment by maximilianriemensberger** [comment]
BTW jupyter notebooks might also work with the IPyKernel. But I haven't tried.

**Comment by maximilianriemensberger** [comment]
Example from todays ipython session (with a few fixes aleady applied on the fly)
```
In [3]: if True:
   ...:     from pypck.connection import PchkConnectionManager
   ...:     from pypck.lcn_addr import LcnAddr
   ...:     import asyncio
   ...:     connection = PchkConnectionManager('10.254.0.1', 4224, 'lcn', 'lcn')
   ...:     await connection.async_connect()

In [4]: module = connection.get_address_conn(LcnAddr(seg_id=0,addr_id=58,is_group=False))

In [5]: module.dyn_text(3, "asdf")
Out[5]: <coroutine object AbstractConnection.dyn_text at 0x7f0951f40940>

In [6]: await module.dyn_text(3, "asdf")
Out[6]: True
```
