### ISSUE TITLE
PckGenerator Motor commands

### ISSUE THREAD

**Issue by maximilianriemensberger** [alengwenus/pypck#42]
While writing tests for the PckGenerator I ran into the following two issues:

* https://github.com/alengwenus/pypck/blob/634c2f6adfd4881bce098e036cba7901db68b813/pypck/lcn_defs.py#L1170-L1182 `TOGGLEDIR` is identical to `DOWN` which blows up https://github.com/alengwenus/pypck/blob/634c2f6adfd4881bce098e036cba7901db68b813/pypck/pck_commands.py#L487

* https://github.com/alengwenus/pypck/blob/634c2f6adfd4881bce098e036cba7901db68b813/pypck/pck_commands.py#L490-L492 does not work since we have OFF,DOWN -> ON,UP -> OFF,DOWN -> ON,UP -> ... (or ON,DOWN -> OFF,UP -> ..., depending on the initial state of the relays).

What about the `RLM` command instead of recreating the motor controls with `R8` commands? Is there any known issues with `RLM`?

(Side note: I have not yet tested either of the commands R8  and RLM.)

**Comment by maximilianriemensberger** [comment]
Ah ... Does the RLM command require a BS4 current sensor?

**Comment by alengwenus** [comment]
Yes, it does. 😉

**Comment by maximilianriemensberger** [comment]
Regarding the `CYCLE`, I probably misunderstood: Am I supposed to do `CYCLE`->`STOP`->`CYCLE`->`STOP`?  (stop might also be a timer, I guess). Anyway, I  got confused about `CYCLE`. :shrug:

**Comment by alengwenus** [comment]
When using the `control_motors_relays()` it is assumed that the corresponding relays were programmed as shutters in LCN-Pro. 
If this is the case the internal logic of the module handles the toggle on both relays exactly as it is expected for a `CYCLE` (and is also aware of the initital relays states).

**Comment by maximilianriemensberger** [comment]
Ok that makes sense. I was assuming the module would just be dumb and use the commands verbatim.
