### ISSUE TITLE
Dumping and restoring bus topology and module/group details

### ISSUE THREAD

**Issue by maximilianriemensberger** [alengwenus/pypck#57]
One use case I envision for pypck (or alternatively something built on top of it) is monitoring the health of a deployment. This would include having knowledge of the bus topology as it should be (modules, groups, segments), regularly checking the presence and/or health of modules and being able to dump the topology as it is right now.

@alengwenus Is there any interest from your side in having such functionality inside pypck? At least dumping (e.g. to json), restoring (e.g. from json, e.g. at `PckConnectionManager` instantiation time), and optional module pinging functionality might be generally useful.

**Comment by alengwenus** [comment]
My intention with pypck was mainly that it should be an interface library to HomeAssistant. Implementing more features into pypck is ok for me as long as it does not break functionality with respect to HomeAssistant. But me for myself will focus on making HomeAssistant the best open source alternative for LCN. 😊
But I am pleased to review PRs with new features.
Btw.: The dumping feature sounds great! 😀
