### ISSUE TITLE
Remove support for Python 3.7

### ISSUE THREAD

**Issue by alengwenus** [alengwenus/pypck#63]
Dropping support for Python 3.7 would allow for some architectural changes:

- All `asyncio` tasks could be tagged with the name parameter. Therefore `pypck` does not need to keep references to dangling tasks as `asyncio` does this for us.
- Tests could rely on the built-in `AsyncMock` object. Therefore the `asynctest` module could be removed which caused errors in Python 3.8 under certain circumstances.

In addition HomeAssistant removed support for Python 3.7 in v0.118.
At least a deprecation warning should be raised in the next release of `pypck`.

**Comment by maximilianriemensberger** [comment]
For what it's worth I don't mind.

**Comment by maximilianriemensberger** [comment]
> * All `asyncio` tasks could be tagged with the name parameter. Therefore `pypck` does not need to keep references to dangling tasks as `asyncio` does this for us.

Wouldn't `set_name()` achieve the same in 3.7?

**Comment by alengwenus** [comment]
Resolved with #70.
