### ISSUE TITLE
Modules do not send an acknowledge using the LEER command

### ISSUE THREAD

**Issue by alengwenus** [alengwenus/pypck#67]
When sending `>G000003!LEER` (`module_scan`) not all modules seem to send an acknowledge if there is lots of bus traffic.

LCN-PRO performs the scan using a different telegram which corresponds to `>G000003.X27EFF06` (request last modification) and observes the responses to that (`=Msssmmm.[tt]`,  `[tt]` = name and encoded date).

It would be interesting if the described behavior also shows up using LCN-PRO.
If not, module scan in `PchkConnectionManager` should be adapted.

**Comment by maximilianriemensberger** [comment]
Just to clarify, I experienced it with other messages as well. So I don't think its a particular problem with `LEER`. More a general problem that all modules try to access the bus simultaneously.

And yes, If I scan my bus with the PRO changes are that I miss one or two modules. I usually rescan them manually.
