### ISSUE TITLE
Featurerequest: SendKeys A1 - J8

### ISSUE THREAD

**Issue by maverickme** [alengwenus/pypck#78]
Hi,

is it possible to extend the key Table from A1 to J8 instead of A1 to D8.

Modules like GT4D use this I1 - J8 keys for the touchswitches.

So i can configure LCN automations on the displaykey and use it in Home Assistant and i dont have to implement the automation/logic twice.

**Comment by alengwenus** [comment]
Hi @maverickme,
thanks for using pypck and for your feature request.

Unfortunately I am not aware of any PCK command or bus telegram to send keys beyond table D.
Even LCN Pro does not allow to send appropriate commands.
I guess that's a hard limitation which prevents the implementation of the requested feature.

**Comment by alengwenus** [comment]
Maybe I have a suggestion for a solution:
You could use LCN-Pro to copy your programmings from the I/J table to keys in table A-D.
Then you could trigger those keys from the respective keys in the I/J table and also from Home Assistant.
